//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gioithieuvieclam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoUngTuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSoUngTuyen()
        {
            this.UngViens = new HashSet<UngVien>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public string HocVan { get; set; }
        public string KinhNghiemLamViec { get; set; }
        public Nullable<bool> KetQua { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngVien> UngViens { get; set; }
    }
}
