//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gioithieuvieclam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTuyenDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTuyenDung()
        {
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
        public string ThongTinLienHe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
