//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gioithieuvieclam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.HoSoUngTuyens = new HashSet<HoSoUngTuyen>();
            this.UngViens = new HashSet<UngVien>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string SoCCCD { get; set; }
        public string DiaChi { get; set; }
        public string TrinhDo { get; set; }
        public string ViTri { get; set; }
        public Nullable<decimal> MucLuongMongMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoUngTuyen> HoSoUngTuyens { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngVien> UngViens { get; set; }
    }
}
