//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gioithieuvieclam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UngVien
    {
        public int ID { get; set; }
        public Nullable<int> CongViecID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public Nullable<int> HoSoID { get; set; }
    
        public virtual CongViec CongViec { get; set; }
        public virtual HoSoUngTuyen HoSoUngTuyen { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
